package application.Ep1Murder;

import java.net.URL;
import java.util.*;
import application.SoundBox;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import application.SoundBox;
import javafx.scene.layout.VBox ;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundImage;
import javafx.scene.layout.BackgroundPosition;
import javafx.scene.layout.BackgroundRepeat;
import javafx.scene.layout.BackgroundSize;
import javafx.scene.layout.BorderPane;


public class Ep1Murder2 extends Application{
	//Point And Click Niña Muerta

    
	//Autogenerated Scene Builder

  		@FXML // ResourceBundle that was given to the FXMLLoader
  	    private ResourceBundle resources;

  	    @FXML // URL location of the FXML file that was given to the FXMLLoader
  	    private URL location;

  	    @FXML // fx:id="investigarcuchillo"
  	    private Button investigarcuchillo; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarcuerpo"
  	    private Button investigarcuerpo; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarmano"
  	    private Button investigarmano; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsala"
  	    private Button investigarsala; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsangre"
  	    private Button investigarsangre; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsuelo"
  	    //private static Button investigarsuelo; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsuelo1"
  	    //private Button investigarsuelo1; // Value injected by FXMLLoader

  	    @FXML // fx:id="labelSuelo"
  	   // private static Label labelSuelo= new Label (); // Value injected by FXMLLoader
  	    
    //Prueba
    	Button investigarsuelo = new Button ();
    	Label labelSuelo= new Label ();
    	labelSuelo.setVisible (false);
    	investigarsuelo.setOnAction (event -> { labelSuelo.setVisible (true);});
    	VBox rootu = new VBox (investigarsuelo, labelSuelo);
  	    
  	    
//________________________________________________________________________________________________________________________________________________________________________________________________________ 
  	//Método para el control de la ventana
  	    
    public void start(Stage primaryStage) throws Exception {

        FXMLLoader loader = new FXMLLoader(getClass().getResource("Ep1NinaMuerta.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Episodio 1");
        primaryStage.setResizable(true); // Se puede redimensionar
        primaryStage.setFullScreen(true); // Abre la ventana en pantalla completa
        primaryStage.setMinWidth(800); // Establece el ancho mínimo de la ventana en 800px
        primaryStage.setMinHeight(600); // Establece la altura mínima de la ventana en 600px
       
        //Mostramos ventana
        primaryStage.show();
    }
   
 //________________________________________________________________________________________________________________________________________________________________________________________________________    
    //
     
    public static void initialize() {
    	
    	//Probamos a crear los botones y la label de nuevo
    	Button investigarcuchillo =new Button ();
    	Button investigarcuerpo =new Button ();
    	Button investigarmano =new Button ();
    	Button investigarsala =new Button ();
    	Button investigarsangre =new Button ();
    	Button investigarsuelo =new Button ();
    	Label labelSuelo = new Label ();
    	
    	//Autogenerado por  Scene Builder
        assert investigarcuchillo != null : "fx:id=\"investigarcuchillo\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert investigarcuerpo != null : "fx:id=\"investigarcuerpo\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert investigarmano != null : "fx:id=\"investigarmano\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert investigarsala != null : "fx:id=\"investigarsala\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert investigarsangre != null : "fx:id=\"investigarsangre\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert investigarsuelo != null : "fx:id=\"investigarsuelo\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
       // assert investigarsuelo1 != null : "fx:id=\"investigarsuelo1\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";
        assert labelSuelo != null : "fx:id=\"labelSuelo\" was not injected: check your FXML file 'Ep1NinaMuerta.fxml'.";

  	    // Hace visible la etiqueta al hacer clic en el botón "investigarsuelo"
        

    }	
	
//________________________________________________________________________________________________________________________________________________________________________________________________________
    public static void main(String[] args) {
        launch(args);

    }    

}
