package application.Ep1Murder;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.DialogPane;

public class Ep1NinaMuerta {
	
		//Autogenerated Scene Builder
	    @FXML
	    private ResourceBundle resources;

	    @FXML
	    private URL location;

	    @FXML
	    private Button investigarcuchillo;

	    @FXML
	    private Button investigarcuerpo;

	    @FXML
	    private Button investigarmano;

	    @FXML
	    private Button investigarsala;

	    @FXML
	    private Button investigarsangre;

	    @FXML
	    private Button investigarsuelo;

	    @FXML
	    private Button investigarsuelo1;

	    @FXML
	    private DialogPane testsala;

	    @FXML
	    private DialogPane textcuchilo;

	    @FXML
	    private DialogPane textcuerpo;

	    @FXML
	    private DialogPane textmano;

	    @FXML
	    private DialogPane textsangre;

	    @FXML
	    private DialogPane textsuelo;

	    
	    @FXML
	    void initialize() {
	    	//Botones
	        assert investigarcuchillo != null : "fx:id=\"investigarcuchillo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarcuerpo != null : "fx:id=\"investigarcuerpo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarmano != null : "fx:id=\"investigarmano\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarsala != null : "fx:id=\"investigarsala\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarsangre != null : "fx:id=\"investigarsangre\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarsuelo != null : "fx:id=\"investigarsuelo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarsuelo1 != null : "fx:id=\"investigarsuelo1\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        //Labels
	        assert testsala != null : "fx:id=\"testsala\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert textcuchilo != null : "fx:id=\"textcuchilo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert textcuerpo != null : "fx:id=\"textcuerpo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert textsangre != null : "fx:id=\"textsangre\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert textsuelo != null : "fx:id=\"textsuelo\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        assert investigarmano != null : "fx:id=\"investigarmano\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        
	        //Hacer que el texto de investigar mano sea visible cuando se pulse el boton (CHAT GPT)

	        assert textmano != null : "fx:id=\"textmano\" was not injected: check your FXML file 'EP1NinaMuerta.fxml'.";
	        investigarmano.setOnAction(event -> {
	            textmano.setVisible(true);
	        });
	    }



}
