package trash;

import java.net.URL;
import java.util.*;
import application.SoundBox;
import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import application.SoundBox;
import javafx.scene.control.Button;
import javafx.scene.control.Label;


public class Ep1Murder extends Application{
	//Point And Click Niña Muerta

    
	//Autogenerated Scene Builder

  		@FXML // ResourceBundle that was given to the FXMLLoader
  	    private ResourceBundle resources;

  	    @FXML // URL location of the FXML file that was given to the FXMLLoader
  	    private URL location;

  	    @FXML // fx:id="investigarcuchillo"
  	    private Button investigarcuchillo; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarcuerpo"
  	    private Button investigarcuerpo; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarmano"
  	    private Button investigarmano; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsala"
  	    private Button investigarsala; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsangre"
  	    private Button investigarsangre; // Value injected by FXMLLoader

  	    @FXML // fx:id="investigarsuelo"
  	    private Button investigarsuelo; // Value injected by FXMLLoader
  	    void investigarSuelo(ActionEvent event) {
  	    	labelSuelo.setVisible(true); // Hace visible la etiqueta al hacer clic en el botón "investigarsuelo"
  	    }

  	    @FXML // fx:id="investigarsuelo1"
  	    private Button investigarsuelo1; // Value injected by FXMLLoader

  	    @FXML // fx:id="labelSuelo"
  	    private Label labelSuelo; // Value injected by FXMLLoader
  	    
  	    
//________________________________________________________________________________________________________________________________________________________________________________________________________ 
  	//Método para el control de la ventana
  	    
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("Ep1NinaMuerta.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Episodio 1");
		primaryStage.setResizable(true); // Se puede redimensionar
		primaryStage.setFullScreen(true); // Abre la ventana en pantalla completa
		primaryStage.setMinWidth(800); // Establece el ancho mínimo de la ventana en 800px
		primaryStage.setMinHeight(600); // Establece la altura mínima de la ventana en 600px
		
		//Ponemos la label para que no sea visible
		labelSuelo.setOpacity(0);
		
		//Mostramnos ventana
        primaryStage.show();
    }
    
 //________________________________________________________________________________________________________________________________________________________________________________________________________    
    //Metodos de control de la visibilidad de la label
    
    void esconderLabel (Label control) {
        control.setVisible(false);
        control.setManaged(false);
    }
	void mostrarLabel (Label control) {
	    control.setVisible(true);
	    control.setManaged(true);
	}
	
	
//________________________________________________________________________________________________________________________________________________________________________________________________________
    public static void main(String[] args) {
        launch(args);
        

    }
    

	    

}
