package Trash;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.*;
import javafx.scene.*;

public class Ep1NinaMuerta {

	//Autogenerated Scene Builder

		@FXML // ResourceBundle that was given to the FXMLLoader
	    private ResourceBundle resources;

	    @FXML // URL location of the FXML file that was given to the FXMLLoader
	    private URL location;

	    @FXML // fx:id="investigarcuchillo"
	    private Button investigarcuchillo; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarcuerpo"
	    private Button investigarcuerpo; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarmano"
	    private Button investigarmano; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarsala"
	    private Button investigarsala; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarsangre"
	    private Button investigarsangre; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarsuelo"
	    private Button investigarsuelo; // Value injected by FXMLLoader

	    @FXML // fx:id="investigarsuelo1"
	    private Button investigarsuelo1; // Value injected by FXMLLoader

	    @FXML // fx:id="labelSuelo"
	    private Label labelSuelo; // Value injected by FXMLLoader

	    @FXML // This method is called by the FXMLLoader when initialization is complete
	    void initialize() {


	    }

	}
